# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(-1, 'Unknown'), (0, 'Any'), (1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
