# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipcode', to='pricing.Clinic'),
        ),
    ]
