# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
