# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20170408_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='qualification_ptr',
        ),
        migrations.RemoveField(
            model_name='award',
            name='qualification_ptr',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='qualification_ptr',
        ),
        migrations.RemoveField(
            model_name='education',
            name='qualification_ptr',
        ),
        migrations.RemoveField(
            model_name='language',
            name='qualification_ptr',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='qualification_ptr',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/profile_pic.jpg', null=True, upload_to=pricing.models.doctor_img_directory_path),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
