# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_affiliation_award_certification_education_language_speciality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'get_latest_by': 'id'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pricing.Service'),
            preserve_default=False,
        ),
    ]
