# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20170409_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price_high',
            new_name='avg_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_low',
        ),
    ]
