# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_auto_20170411_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_score',
            field=models.IntegerField(choices=[(1, b'Really Bad'), (2, b'Below Average'), (3, b'Average'), (4, b'Above Average'), (5, b'Amazing')], default=4),
            preserve_default=False,
        ),
    ]
