# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_review_overall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_leads', to='pricing.DoctorProfile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_leads', to='pricing.Service')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_leads', to='pricing.UserProfile')),
            ],
        ),
    ]
