# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_appointmentlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_type', models.IntegerField(choices=[(1, 'More Info'), (2, 'Appt Info')])),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='pricing.DoctorProfile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='pricing.Service')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='pricing.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentlead',
            name='doctor_profile',
        ),
        migrations.RemoveField(
            model_name='appointmentlead',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointmentlead',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='click',
            name='service',
        ),
        migrations.RemoveField(
            model_name='click',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppointmentLead',
        ),
        migrations.DeleteModel(
            name='Click',
        ),
    ]
