# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_auto_20170411_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='doctor_profile',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='user_profile',
            new_name='user',
        ),
    ]
