# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_auto_20170412_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xx', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xx', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xx', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xx', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='state',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='code',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='name',
            field=models.CharField(default='xx', max_length=20),
        ),
        migrations.AddField(
            model_name='search',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='pricing.City'),
        ),
    ]
