# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_auto_20170412_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='pricing.City'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='pricing.Country'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='pricing.Neighborhood'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='pricing.State'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='zipcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='pricing.Zipcode'),
        ),
    ]
