# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_auto_20170412_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='award',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certification',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='procedure',
            name='slug',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='specialty',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='slug',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
