# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_auto_20170412_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pricing.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='pricing.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='pricing.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zipcode',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='zipcodes', to='pricing.City'),
            preserve_default=False,
        ),
    ]
