# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_auto_20170416_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='source',
            field=models.CharField(default='/', max_length=50),
        ),
    ]
