# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_auto_20170416_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='practice_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
