# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0028_doctorprofile_practice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='pricing.Procedure'),
        ),
        migrations.AddField(
            model_name='category',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pricing.Procedure'),
        ),
    ]
