# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_auto_20170416_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='fair_price',
            new_name='free_market_price',
        ),
        migrations.AddField(
            model_name='procedure',
            name='billed_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='procedure',
            name='insurer_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
