# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0030_auto_20170416_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='billed_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='free_market_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='insurer_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
