# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0031_auto_20170416_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='procedure',
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='pricing.Category'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='pricing.Subcategory'),
        ),
    ]
