# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0032_auto_20170416_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='desc',
            field=models.CharField(default='default desciriptn of all procesdures', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedure',
            name='slug',
            field=models.CharField(max_length=30),
        ),
    ]
