# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0033_auto_20170416_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Cancelled'), (3, 'Scheduled'), (4, 'Completed')], default=1),
        ),
    ]
