# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0034_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Cancelled'), (3, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, default='defaults/procedure.jpg', null=True, upload_to=pricing.models.procedure_img_directory_path),
        ),
    ]
