# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 01:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pricing.models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0035_auto_20170418_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pricing.models.blog_img_directory_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pricing.models.doctor_img_directory_path),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Cancelled'), (3, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pricing.models.procedure_img_directory_path),
        ),
    ]
