# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0036_auto_20170420_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepoint',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pricepoint',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.Procedure'),
        ),
        migrations.AddField(
            model_name='pricepoint',
            name='zipcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.Zipcode'),
        ),
        migrations.AlterField(
            model_name='pricepoint',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='pricing.Service'),
        ),
    ]
